// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package edu.uiuc.cs414.group8desktop;

public final class DataProto {
  private DataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class DataPacket extends
      com.google.protobuf.GeneratedMessage {
    // Use DataPacket.newBuilder() to construct.
    private DataPacket() {
      initFields();
    }
    private DataPacket(boolean noInit) {}
    
    private static final DataPacket defaultInstance;
    public static DataPacket getDefaultInstance() {
      return defaultInstance;
    }
    
    public DataPacket getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uiuc.cs414.group8desktop.DataProto.internal_static_tutorial_DataPacket_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uiuc.cs414.group8desktop.DataProto.internal_static_tutorial_DataPacket_fieldAccessorTable;
    }
    
    public enum PacketType
        implements com.google.protobuf.ProtocolMessageEnum {
      VIDEO(0, 0),
      AUDIO(1, 1),
      CONTROL(2, 2),
      PING(3, 3),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static PacketType valueOf(int value) {
        switch (value) {
          case 0: return VIDEO;
          case 1: return AUDIO;
          case 2: return CONTROL;
          case 3: return PING;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PacketType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
              public PacketType findValueByNumber(int number) {
                return PacketType.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.uiuc.cs414.group8desktop.DataProto.DataPacket.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final PacketType[] VALUES = {
        VIDEO, AUDIO, CONTROL, PING, 
      };
      public static PacketType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private PacketType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        edu.uiuc.cs414.group8desktop.DataProto.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:tutorial.DataPacket.PacketType)
    }
    
    public enum ControlCode
        implements com.google.protobuf.ProtocolMessageEnum {
      UP(0, 0),
      DOWN(1, 1),
      LEFT(2, 2),
      RIGHT(3, 3),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static ControlCode valueOf(int value) {
        switch (value) {
          case 0: return UP;
          case 1: return DOWN;
          case 2: return LEFT;
          case 3: return RIGHT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ControlCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ControlCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ControlCode>() {
              public ControlCode findValueByNumber(int number) {
                return ControlCode.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.uiuc.cs414.group8desktop.DataProto.DataPacket.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final ControlCode[] VALUES = {
        UP, DOWN, LEFT, RIGHT, 
      };
      public static ControlCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private ControlCode(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        edu.uiuc.cs414.group8desktop.DataProto.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:tutorial.DataPacket.ControlCode)
    }
    
    // required int64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // required int64 servertime = 2;
    public static final int SERVERTIME_FIELD_NUMBER = 2;
    private boolean hasServertime;
    private long servertime_ = 0L;
    public boolean hasServertime() { return hasServertime; }
    public long getServertime() { return servertime_; }
    
    // required .tutorial.DataPacket.PacketType type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private boolean hasType;
    private edu.uiuc.cs414.group8desktop.DataProto.DataPacket.PacketType type_;
    public boolean hasType() { return hasType; }
    public edu.uiuc.cs414.group8desktop.DataProto.DataPacket.PacketType getType() { return type_; }
    
    // optional bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private boolean hasData;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasData() { return hasData; }
    public com.google.protobuf.ByteString getData() { return data_; }
    
    // optional .tutorial.DataPacket.ControlCode control = 5;
    public static final int CONTROL_FIELD_NUMBER = 5;
    private boolean hasControl;
    private edu.uiuc.cs414.group8desktop.DataProto.DataPacket.ControlCode control_;
    public boolean hasControl() { return hasControl; }
    public edu.uiuc.cs414.group8desktop.DataProto.DataPacket.ControlCode getControl() { return control_; }
    
    // optional int32 pingid = 6;
    public static final int PINGID_FIELD_NUMBER = 6;
    private boolean hasPingid;
    private int pingid_ = 0;
    public boolean hasPingid() { return hasPingid; }
    public int getPingid() { return pingid_; }
    
    private void initFields() {
      type_ = edu.uiuc.cs414.group8desktop.DataProto.DataPacket.PacketType.VIDEO;
      control_ = edu.uiuc.cs414.group8desktop.DataProto.DataPacket.ControlCode.UP;
    }
    public final boolean isInitialized() {
      if (!hasTimestamp) return false;
      if (!hasServertime) return false;
      if (!hasType) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasTimestamp()) {
        output.writeInt64(1, getTimestamp());
      }
      if (hasServertime()) {
        output.writeInt64(2, getServertime());
      }
      if (hasType()) {
        output.writeEnum(3, getType().getNumber());
      }
      if (hasData()) {
        output.writeBytes(4, getData());
      }
      if (hasControl()) {
        output.writeEnum(5, getControl().getNumber());
      }
      if (hasPingid()) {
        output.writeInt32(6, getPingid());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getTimestamp());
      }
      if (hasServertime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getServertime());
      }
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, getType().getNumber());
      }
      if (hasData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getData());
      }
      if (hasControl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, getControl().getNumber());
      }
      if (hasPingid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, getPingid());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.uiuc.cs414.group8desktop.DataProto.DataPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.DataPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.DataPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.DataPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.DataPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.DataPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.DataPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.DataPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.DataPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.DataPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.uiuc.cs414.group8desktop.DataProto.DataPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.uiuc.cs414.group8desktop.DataProto.DataPacket result;
      
      // Construct using edu.uiuc.cs414.group8desktop.DataProto.DataPacket.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.uiuc.cs414.group8desktop.DataProto.DataPacket();
        return builder;
      }
      
      protected edu.uiuc.cs414.group8desktop.DataProto.DataPacket internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.uiuc.cs414.group8desktop.DataProto.DataPacket();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uiuc.cs414.group8desktop.DataProto.DataPacket.getDescriptor();
      }
      
      public edu.uiuc.cs414.group8desktop.DataProto.DataPacket getDefaultInstanceForType() {
        return edu.uiuc.cs414.group8desktop.DataProto.DataPacket.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.uiuc.cs414.group8desktop.DataProto.DataPacket build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.uiuc.cs414.group8desktop.DataProto.DataPacket buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.uiuc.cs414.group8desktop.DataProto.DataPacket buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        edu.uiuc.cs414.group8desktop.DataProto.DataPacket returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uiuc.cs414.group8desktop.DataProto.DataPacket) {
          return mergeFrom((edu.uiuc.cs414.group8desktop.DataProto.DataPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.uiuc.cs414.group8desktop.DataProto.DataPacket other) {
        if (other == edu.uiuc.cs414.group8desktop.DataProto.DataPacket.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasServertime()) {
          setServertime(other.getServertime());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasControl()) {
          setControl(other.getControl());
        }
        if (other.hasPingid()) {
          setPingid(other.getPingid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setTimestamp(input.readInt64());
              break;
            }
            case 16: {
              setServertime(input.readInt64());
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              edu.uiuc.cs414.group8desktop.DataProto.DataPacket.PacketType value = edu.uiuc.cs414.group8desktop.DataProto.DataPacket.PacketType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 34: {
              setData(input.readBytes());
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              edu.uiuc.cs414.group8desktop.DataProto.DataPacket.ControlCode value = edu.uiuc.cs414.group8desktop.DataProto.DataPacket.ControlCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                setControl(value);
              }
              break;
            }
            case 48: {
              setPingid(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int64 timestamp = 1;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // required int64 servertime = 2;
      public boolean hasServertime() {
        return result.hasServertime();
      }
      public long getServertime() {
        return result.getServertime();
      }
      public Builder setServertime(long value) {
        result.hasServertime = true;
        result.servertime_ = value;
        return this;
      }
      public Builder clearServertime() {
        result.hasServertime = false;
        result.servertime_ = 0L;
        return this;
      }
      
      // required .tutorial.DataPacket.PacketType type = 3;
      public boolean hasType() {
        return result.hasType();
      }
      public edu.uiuc.cs414.group8desktop.DataProto.DataPacket.PacketType getType() {
        return result.getType();
      }
      public Builder setType(edu.uiuc.cs414.group8desktop.DataProto.DataPacket.PacketType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = edu.uiuc.cs414.group8desktop.DataProto.DataPacket.PacketType.VIDEO;
        return this;
      }
      
      // optional bytes data = 4;
      public boolean hasData() {
        return result.hasData();
      }
      public com.google.protobuf.ByteString getData() {
        return result.getData();
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasData = true;
        result.data_ = value;
        return this;
      }
      public Builder clearData() {
        result.hasData = false;
        result.data_ = getDefaultInstance().getData();
        return this;
      }
      
      // optional .tutorial.DataPacket.ControlCode control = 5;
      public boolean hasControl() {
        return result.hasControl();
      }
      public edu.uiuc.cs414.group8desktop.DataProto.DataPacket.ControlCode getControl() {
        return result.getControl();
      }
      public Builder setControl(edu.uiuc.cs414.group8desktop.DataProto.DataPacket.ControlCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasControl = true;
        result.control_ = value;
        return this;
      }
      public Builder clearControl() {
        result.hasControl = false;
        result.control_ = edu.uiuc.cs414.group8desktop.DataProto.DataPacket.ControlCode.UP;
        return this;
      }
      
      // optional int32 pingid = 6;
      public boolean hasPingid() {
        return result.hasPingid();
      }
      public int getPingid() {
        return result.getPingid();
      }
      public Builder setPingid(int value) {
        result.hasPingid = true;
        result.pingid_ = value;
        return this;
      }
      public Builder clearPingid() {
        result.hasPingid = false;
        result.pingid_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.DataPacket)
    }
    
    static {
      defaultInstance = new DataPacket(true);
      edu.uiuc.cs414.group8desktop.DataProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.DataPacket)
  }
  
  public static final class ControlPacket extends
      com.google.protobuf.GeneratedMessage {
    // Use ControlPacket.newBuilder() to construct.
    private ControlPacket() {
      initFields();
    }
    private ControlPacket(boolean noInit) {}
    
    private static final ControlPacket defaultInstance;
    public static ControlPacket getDefaultInstance() {
      return defaultInstance;
    }
    
    public ControlPacket getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uiuc.cs414.group8desktop.DataProto.internal_static_tutorial_ControlPacket_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uiuc.cs414.group8desktop.DataProto.internal_static_tutorial_ControlPacket_fieldAccessorTable;
    }
    
    public enum ControlType
        implements com.google.protobuf.ProtocolMessageEnum {
      DEFAULT(0, 0),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static ControlType valueOf(int value) {
        switch (value) {
          case 0: return DEFAULT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ControlType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ControlType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ControlType>() {
              public ControlType findValueByNumber(int number) {
                return ControlType.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.uiuc.cs414.group8desktop.DataProto.ControlPacket.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final ControlType[] VALUES = {
        DEFAULT, 
      };
      public static ControlType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private ControlType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        edu.uiuc.cs414.group8desktop.DataProto.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:tutorial.ControlPacket.ControlType)
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.uiuc.cs414.group8desktop.DataProto.ControlPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.ControlPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.ControlPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.ControlPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.ControlPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.ControlPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.ControlPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.ControlPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.ControlPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uiuc.cs414.group8desktop.DataProto.ControlPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.uiuc.cs414.group8desktop.DataProto.ControlPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.uiuc.cs414.group8desktop.DataProto.ControlPacket result;
      
      // Construct using edu.uiuc.cs414.group8desktop.DataProto.ControlPacket.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.uiuc.cs414.group8desktop.DataProto.ControlPacket();
        return builder;
      }
      
      protected edu.uiuc.cs414.group8desktop.DataProto.ControlPacket internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.uiuc.cs414.group8desktop.DataProto.ControlPacket();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uiuc.cs414.group8desktop.DataProto.ControlPacket.getDescriptor();
      }
      
      public edu.uiuc.cs414.group8desktop.DataProto.ControlPacket getDefaultInstanceForType() {
        return edu.uiuc.cs414.group8desktop.DataProto.ControlPacket.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.uiuc.cs414.group8desktop.DataProto.ControlPacket build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.uiuc.cs414.group8desktop.DataProto.ControlPacket buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.uiuc.cs414.group8desktop.DataProto.ControlPacket buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        edu.uiuc.cs414.group8desktop.DataProto.ControlPacket returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uiuc.cs414.group8desktop.DataProto.ControlPacket) {
          return mergeFrom((edu.uiuc.cs414.group8desktop.DataProto.ControlPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.uiuc.cs414.group8desktop.DataProto.ControlPacket other) {
        if (other == edu.uiuc.cs414.group8desktop.DataProto.ControlPacket.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:tutorial.ControlPacket)
    }
    
    static {
      defaultInstance = new ControlPacket(true);
      edu.uiuc.cs414.group8desktop.DataProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.ControlPacket)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_DataPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_DataPacket_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ControlPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_ControlPacket_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022\010tutorial\"\244\002\n\nDataPacket\022\021\n" +
      "\ttimestamp\030\001 \002(\003\022\022\n\nservertime\030\002 \002(\003\022-\n\004" +
      "type\030\003 \002(\0162\037.tutorial.DataPacket.PacketT" +
      "ype\022\014\n\004data\030\004 \001(\014\0221\n\007control\030\005 \001(\0162 .tut" +
      "orial.DataPacket.ControlCode\022\016\n\006pingid\030\006" +
      " \001(\005\"9\n\nPacketType\022\t\n\005VIDEO\020\000\022\t\n\005AUDIO\020\001" +
      "\022\013\n\007CONTROL\020\002\022\010\n\004PING\020\003\"4\n\013ControlCode\022\006" +
      "\n\002UP\020\000\022\010\n\004DOWN\020\001\022\010\n\004LEFT\020\002\022\t\n\005RIGHT\020\003\"+\n" +
      "\rControlPacket\"\032\n\013ControlType\022\013\n\007DEFAULT" +
      "\020\000B)\n\034edu.uiuc.cs414.group8desktopB\tData",
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_DataPacket_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_DataPacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_DataPacket_descriptor,
              new java.lang.String[] { "Timestamp", "Servertime", "Type", "Data", "Control", "Pingid", },
              edu.uiuc.cs414.group8desktop.DataProto.DataPacket.class,
              edu.uiuc.cs414.group8desktop.DataProto.DataPacket.Builder.class);
          internal_static_tutorial_ControlPacket_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tutorial_ControlPacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_ControlPacket_descriptor,
              new java.lang.String[] { },
              edu.uiuc.cs414.group8desktop.DataProto.ControlPacket.class,
              edu.uiuc.cs414.group8desktop.DataProto.ControlPacket.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
